# Generated by Django 6.0.5 on 2026-06-02 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('input_example', models.TextField(blank=True)),
                ('output_example', models.TextField(blank=True)),
                ('time_limit', models.IntegerField(default=1000)),
                ('memory_limit', models.IntegerField(default=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(blank=True, null=True)),
                ('index', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=500)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('problemset_name', models.CharField(blank=True, max_length=200)),
                ('problem_type', models.CharField(default='PROGRAMMING', max_length=50)),
                ('points', models.FloatField(blank=True, null=True)),
                ('solved_count', models.IntegerField(default=0)),
                ('platform', models.CharField(default='codeforces', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-contest_id', 'index'],
                'unique_together': {('contest_id', 'index', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('target_rating', models.IntegerField()),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'id')},
            },
        ),
        migrations.CreateModel(
            name='SavedProblem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contest_id', models.IntegerField(blank=True, null=True)),
                ('index', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=500)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('todo', '待做'), ('attempting', '尝试中'), ('solved', '已解决')], default='todo', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(default='codeforces', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'id')},
            },
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='api.trainingplan')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('training_plan', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('luogu', '洛谷'), ('nowcoder', '牛客')], default='codeforces', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('max_rating', models.IntegerField(blank=True, null=True)),
                ('avatar', models.URLField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating'],
                'unique_together': {('user', 'handle', 'platform')},
            },
        ),
    ]
