# Generated by Django 6.0.5 on 2026-06-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproblem',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('luogu', '洛谷'), ('nowcoder', '牛客'), ('other', '其他')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('luogu', '洛谷'), ('nowcoder', '牛客'), ('other', '其他')], default='codeforces', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedproblem',
            name='platform',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('atcoder', 'AtCoder'), ('luogu', '洛谷'), ('nowcoder', '牛客'), ('other', '其他')], default='codeforces', max_length=20),
        ),
    ]
