# Generated by Django 6.0.5 on 2026-06-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customproblem_platform_alter_problem_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmTemplate',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('基础', '基础'), ('进阶', '进阶'), ('高级', '高级')], default='基础', max_length=20)),
                ('description', models.TextField()),
                ('detailed_description', models.TextField(blank=True)),
                ('time_complexity', models.CharField(max_length=200)),
                ('space_complexity', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('usage', models.TextField(blank=True)),
                ('example_input', models.TextField(blank=True)),
                ('example_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
