# Generated by Django 6.0.5 on 2026-06-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_algorithmtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmtemplate',
            name='tags',
        ),
        migrations.AddField(
            model_name='algorithmtemplate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='templates', to='api.algorithmtag'),
        ),
    ]
