# Generated by Django 6.0.5 on 2026-06-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_algorithmtemplate_tags_algorithmtemplate_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='tags',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='training_plans', to='api.algorithmtag'),
        ),
    ]
