# Generated by Django 6.0.5
# 添加国内赛事训练计划模板

from django.db import migrations


def create_domestic_contest_plans(apps, schema_editor):
    TrainingPlan = apps.get_model('api', 'TrainingPlan')
    AlgorithmTag = apps.get_model('api', 'AlgorithmTag')
    
    plans = [
        {
            'id': 'csp-j',
            'title': 'CSP-J 入门级训练题单',
            'target_rating': 1400,
            'description': 'CSP-J（普及组）是面向初中生的入门级信息学竞赛，重点训练基础算法与程序设计能力。',
            'tags': ['implementation', 'brute force', 'sorting', 'binary search', 'greedy', 'math'],
        },
        {
            'id': 'csp-s',
            'title': 'CSP-S 提高级训练题单',
            'target_rating': 1800,
            'description': 'CSP-S（提高组）是面向高中生的提高级竞赛，重点训练树图算法、动态规划等核心能力。',
            'tags': ['dp', 'dfs and similar', 'graphs', 'data structures', 'trees'],
        },
        {
            'id': 'noip',
            'title': 'NOIP 全国联赛训练题单',
            'target_rating': 2100,
            'description': 'NOIP 是全国性信息学奥赛，需要全面的算法知识与解题技巧，适合省赛及更高水平选手。',
            'tags': ['dp', 'graphs', 'trees', 'data structures', 'combinatorics', 'flows'],
        },
        {
            'id': 'domestic-training',
            'title': '国内赛事综合训练题单',
            'target_rating': 1600,
            'description': '针对 CSP、NOIP 等国内赛事的综合训练计划，涵盖各类高频考点与经典题型。',
            'tags': ['implementation', 'dp', 'greedy', 'math', 'graphs', 'data structures'],
        },
    ]
    
    for plan_data in plans:
        tags_data = plan_data.pop('tags')
        
        plan, created = TrainingPlan.objects.get_or_create(
            id=plan_data['id'],
            defaults=plan_data
        )
        
        for tag_name in tags_data:
            tag, _ = AlgorithmTag.objects.get_or_create(name=tag_name)
            plan.tags.add(tag)


def reverse_create_domestic_contest_plans(apps, schema_editor):
    TrainingPlan = apps.get_model('api', 'TrainingPlan')
    plan_ids = ['csp-j', 'csp-s', 'noip', 'domestic-training']
    TrainingPlan.objects.filter(id__in=plan_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_trainingplan_tags_trainingplan_tags'),
    ]

    operations = [
        migrations.RunPython(create_domestic_contest_plans, reverse_create_domestic_contest_plans),
    ]