# Generated by Django 6.0.5 on 2026-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_domestic_contest_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='badge_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='gradient',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='target_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='topics',
            field=models.JSONField(default=list),
        ),
    ]
