# Generated by Django 6.0.5
# 更新国内赛事训练计划模板数据，添加显示字段

from django.db import migrations


def update_domestic_contest_plans(apps, schema_editor):
    TrainingPlan = apps.get_model('api', 'TrainingPlan')
    
    plans_data = {
        'csp-j': {
            'subtitle': '面向初中级选手的入门竞赛训练',
            'target_count': 30,
            'topics': ['基础模拟', '暴力搜索', '排序算法', '二分查找', '贪心算法', '初等数论'],
            'badge_color': 'bg-blue-50 text-blue-700 border-blue-200',
            'gradient': 'from-blue-400 to-blue-600',
        },
        'csp-s': {
            'subtitle': '面向高中级选手的提高竞赛训练',
            'target_count': 25,
            'topics': ['动态规划', '深广搜索', '图论基础', '基础数据结构', '树结构'],
            'badge_color': 'bg-green-50 text-green-700 border-green-200',
            'gradient': 'from-green-400 to-emerald-600',
        },
        'noip': {
            'subtitle': 'NOIP 全国青少年信息学奥林匹克联赛冲刺训练',
            'target_count': 20,
            'topics': ['高级动态规划', '复杂图论', '高级数据结构', '组合数学', '网络流基础'],
            'badge_color': 'bg-amber-50 text-amber-700 border-amber-200',
            'gradient': 'from-amber-400 to-orange-600',
        },
        'domestic-training': {
            'subtitle': '全面覆盖国内信息学竞赛常考题型',
            'target_count': 40,
            'topics': ['全算法体系', '经典题型', '高频考点', '赛前冲刺'],
            'badge_color': 'bg-purple-50 text-purple-700 border-purple-200',
            'gradient': 'from-purple-400 to-indigo-600',
        },
    }
    
    for plan_id, data in plans_data.items():
        TrainingPlan.objects.filter(id=plan_id).update(**data)


def reverse_update_domestic_contest_plans(apps, schema_editor):
    TrainingPlan = apps.get_model('api', 'TrainingPlan')
    plan_ids = ['csp-j', 'csp-s', 'noip', 'domestic-training']
    TrainingPlan.objects.filter(id__in=plan_ids).update(
        subtitle='',
        target_count=0,
        topics=[],
        badge_color='',
        gradient='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_plan_display_fields'),
    ]

    operations = [
        migrations.RunPython(update_domestic_contest_plans, reverse_update_domestic_contest_plans),
    ]