# Generated by Django 6.0.5 on 2026-06-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_update_domestic_contest_plans_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='topics',
        ),
    ]
